name: Deploy to DigitalOcean

on:
  push:
    branches: ['main']

defaults:
  run:
    working-directory: ./app

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install Meteor
        run: curl https://install.meteor.com/ | sh

      - name: Run npm ci
        run: meteor npm ci --legacy-peer-deps

      - name: Install mup
        run: npm i -g mup

      - name: Build app
        run: meteor npm run build

      - name: Write mup.js content to file
        run: echo "${{ secrets.MUP_JS_CONTENT }}" > ./mup.js
        shell: bash
        working-directory: ./app/.deploy

      - name: Write settings.json content to file
        run: echo '${{ secrets.SETTINGS_JSON_CONTENT }}' > ./settings.json
        shell: bash
        working-directory: ./app/.deploy

      - name: Run mup setup
        run: mup setup
        working-directory: ./app/.deploy

      - name: Run mup stop
        run: mup stop
        working-directory: ./app/.deploy

      - name: Run mup deploy
        run: mup deploy
        working-directory: ./app/.deploy
