name: Testcafe

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

defaults:
  run:
    working-directory: ./app

jobs:
  testcafe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-v5-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - run: npm ci --legacy-peer-deps

      - run: curl https://install.meteor.com/ | sh

      - name: Install wait-on
        run: npm install wait-on --save-dev

      - name: Start the app
        run: meteor npm run start &

      - name: Wait for the app to start
        run: npx wait-on http://localhost:3000

      - name: Run TestCafe tests
        run: npm run testcafe-ci
